### ISSUE TITLE
demo可以跑起来，但是用到项目里就报错了，Invalid prop: type check failed 

### ISSUE THREAD

**Issue by unssnu** [keifc/vue-filter-bar#1]
demo缺少node-sass，自己安装下，demo就可以跑起来~~~~~~~
但是。。。

使用到自己的项目里，报错了
[Vue warn]: Invalid prop: type check failed for prop "barMenus". Expected Array, got Object.

found in

---> <FilterBar> at F:\project\aiways-mobile\node_modules\vue-filter-bar\demo\src\components\FilterBar.vue
       <Carlist> at F:\project\aiways-mobile\src\pages\carlist.vue
         <App> at F:\project\aiways-mobile\src\App.vue... (1 recursive calls)
           <Root>

**Comment by john-blessing** [comment]
下载node-sass需要翻墙 否则很难下下来 把下载地址切换成国内镜像就可以
这是mac的
SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ npm install node-sass

**Comment by unssnu** [comment]
谢谢，可以了，原来是依赖问题 T_T
